### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'git log': 'git log'

### ISSUE THREAD

**Issue by bashu** [thautwarm/fix-author#2]
fix-author fix -fe bashu@1999deec-96d2-416c-8806-2e0b721c1ba4 -te basil.shubin@gmail.com

```traceback
/Users/bashu/.virtualenvs/example/lib/python3.7/site-packages/rbnf/edsl/__init__.py:1: UserWarning: Install yapf to reformat generated code!
  from .core import *
  fix
      log: git log
      fu: from user/author name to change.
      tu: to user/name to be changed to.
      fe: from email/email to change.
      tu: to email/email to be changed to.


  - fu(positional or keyword arg) = None
  - tu(positional or keyword arg) = None
  - fe(positional or keyword arg) = None
  - te(positional or keyword arg) = None

Traceback (most recent call last):
  File "/Users/bashu/.virtualenvs/example/bin/fix-author", line 10, in <module>
    sys.exit(main())
  File "/Users/bashu/.virtualenvs/example/lib/python3.7/site-packages/fix_author/cli.py", line 44, in main
    talking.on()
  File "/Users/bashu/.virtualenvs/example/lib/python3.7/site-packages/wisepy/talking.py", line 159, in on
    self.from_text(recv, {})
  File "/Users/bashu/.virtualenvs/example/lib/python3.7/site-packages/wisepy/talking.py", line 141, in from_text
    result = self.visit(parse(text).result.value, ctx)
  File "<string>", line 8, in new_func
  File "/Users/bashu/.virtualenvs/example/lib/python3.7/site-packages/wisepy/talking.py", line 132, in visit
    raise e
  File "/Users/bashu/.virtualenvs/example/lib/python3.7/site-packages/wisepy/talking.py", line 129, in visit
    return com(*args, **kwargs)
  File "/Users/bashu/.virtualenvs/example/lib/python3.7/site-packages/wisepy/talking.py", line 20, in __call__
    return dynamic_cast(self.fn)(*args, **kwargs)
  File "/Users/bashu/.virtualenvs/example/lib/python3.7/site-packages/wisepy/dynamic_cast.py", line 12, in inner
    return fn(*args, **kwargs)
  File "/Users/bashu/.virtualenvs/example/lib/python3.7/site-packages/fix_author/cli.py", line 21, in fix
    log = check_output('git log').decode()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'git log': 'git log'
```

**Comment by Derkades** [comment]
Same issue on linux, not ina virtual environment, just a regular install using `pip3 install fix-author`. The git commands works fine in the same terminal.
